# Generated by Django 3.1.2 on 2020-10-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='characterClass',
            new_name='character_class',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='characterSubClass',
            new_name='character_subClass',
        ),
        migrations.RenameField(
            model_name='charactersubclass',
            old_name='CharacterClass',
            new_name='character_class',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.campaign'),
            preserve_default=False,
        ),
    ]
