# Generated by Django 3.1.2 on 2020-10-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201029_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterRace',
        ),
    ]
