# Generated by Django 3.1.2 on 2020-11-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_delete_characterrace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersubclass',
            old_name='subClass',
            new_name='name',
        ),
    ]
